export const challenges = [
  {
    id: 1,
    title: "Complete your first goal",
    description: "Mark your first goal as completed",
    difficulty: "easy",
    xp: 100,
    image: "/badges/1_habit.png",
  },
  {
    id: 3,
    title: "Get 5 habits",
    description: "Add 5 habits to your list",
    difficulty: "easy",
    xp: 100,
    image: "/badges/5_habits.png",
  },
  {
    id: 4,
    title: "Add a new habit",
    description: "Add a new habit to track",
    difficulty: "medium",
    xp: 200,
    image: "/badges/starting_1_habit.png",
  },
  {
    id: 5,
    title: "Track a habit for a week",
    description: "Track any habit every day for a week",
    difficulty: "medium",
    xp: 300,
    image: "/badges/1_week.png",
  },
  {
    id: 6,
    title: "Track a habit for a month",
    description: "Track any habit every day for a month",
    difficulty: "hard",
    xp: 500,
    image: "/badges/1_month.png",
  },
  {
    id: 7,
    title: "Share your progress",
    description: "Share your progress with a post",
    difficulty: "medium",
    xp: 200,
    image: "/badges/share_progress.png",
  },
  {
    id: 8,
    title: "Customize your profile",
    description: "Update your profile with a photo and bio",
    difficulty: "easy",
    xp: 100,
  },
  {
    id: 9,
    title: "Complete 50 habits",
    description: "Complete any habits 50 times",
    difficulty: "hard",
    xp: 600,
    image: "/badges/50_habits.png",
  },
  // {
  //     id: 9,
  //     title: "Join a group challenge",
  //     description: "Participate in a group challenge",
  //     difficulty: "medium",
  //     xp: 300
  // },
];
